services:
  invertus.dpdbaltics.adapter.dpdconfiguration_adapter:
    class: 'Invertus\dpdBaltics\Adapter\DPDConfigurationAdapter'

  invertus.dpdbaltics.adapter.zone_adapter:
    class: 'Invertus\dpdBaltics\Adapter\ZoneAdapter'