dpdbaltics_download_printed_label:
  path: /{orderId}/dpdbaltics/generate-dpdbaltics-print-label
  methods: [GET]
  defaults:
    _controller: Invertus\dpdBaltics\Controller\OrderLabelController::printAndSaveLabelAction
    _legacy_controller: AdminOrders
  requirements:
    orderId: \d+

dpdbaltics_print_label:
  path: /{shipmentId}/{labelPosition}/{labelFormat}/dpdbaltics/print-label
  methods: [GET]
  defaults:
    _controller: Invertus\dpdBaltics\Controller\OrderLabelController::printLabelAction
    _legacy_controller: AdminOrders
  requirements:
    shipmentId: \d+
    labelPosition: LeftTop|LeftDown|RightTop|RightDown
    labelFormat: A4_PDF|A5_PDF|A6_PDF|ZPL|EPL

dpdbaltics_download_multiple_printed_labels:
  path: /dpdbaltics/generate-dpdbaltics-multiple-labels
  methods: [POST]
  defaults:
    _controller: Invertus\dpdBaltics\Controller\OrderLabelController::printMultipleLabelsAction
    _legacy_controller: AdminOrders