name: release
on:
  release:
    types: [ published]

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: |
          composer install --no-dev --optimize-autoloader --classmap-authoritative
          composer dump-autoload --no-dev --optimize --classmap-authoritative
          rm -rf .git
          rm -rf .github
          rm -rf tests
          rm -rf vendor.zip
          mkdir dpdbaltics
          rsync -Rr ./ ./dpdbaltics
          shopt -s extglob
          rm -r !(dpdbaltics)
          find . -maxdepth 1 -type f -exec rm "{}" \;
          cd dpdbaltics && rm -rf dpdbaltics
          cd ../ && zip -r dpdbaltics.zip dpdbaltics/
      - name: Update Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./dpdbaltics.zip
